# -*- coding: utf-8 -*-
"""task automation .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZhgcJGWG8kiorrdQkHTKehF0UvDu1InC
"""

#TASK 3: Task Automation (Move JPG Files)
import os
import shutil

source_folder = "images"
destination_folder = "new_imsages"

if not os.path.exists(destination_folder):
    os.mkdir(destination_folder)

files = os.listdir(source_folder)

for file in files:

    if file.endswith(".jpg"):

        source_path = os.path.join(source_folder, file)

        destination_path = os.path.join(destination_folder, file)

        shutil.move(source_path, destination_path)

        print(file, "Moved Successfully")

print("All JPG files have been moved.")